In [38]:
# Dependencies and Setup
import pandas as pd

# File to Load
chart_path = "charts.csv"

# Read Chart Data File and store into Pandas DataFrames
chart_data = pd.read_csv(chart_path)

#print dataframe
chart_data

,title,rank,date,artist,url,region,chart,trend,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,Argentina,top200,SAME_POSITION,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,https://open.spotify.com/track/7DM4BPaS7uofFul...,Argentina,top200,MOVE_UP,223988.0
2,Reggaetón Lento (Bailemos),3,2017-01-01,CNCO,https://open.spotify.com/track/3AEZUABDXNtecAO...,Argentina,top200,MOVE_DOWN,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",https://open.spotify.com/track/6rQSrBHf7HlZjtc...,Argentina,top200,SAME_POSITION,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,https://open.spotify.com/track/58IL315gMSTD37D...,Argentina,top200,MOVE_UP,153956.0
...,...,...,...,...,...,...,...,...,...
26173509,BYE,46,2021-07-31,Jaden,https://open.spotify.com/track/3OUyyDN7EZrL7i0...,Vietnam,viral50,MOVE_UP,NaN
26173510,Pillars,47,2021-07-31,My Anh,https://open.spotify.com/track/6eky30oFiQbHUAT...,Vietnam,viral50,NEW_ENTRY,NaN
26173511,Gái Độc Thân,48,2021-07-31,Tlinh,https://open.spotify.com/track/2klsSb2iTfgDh95...,Vietnam,viral50,MOVE_DOWN,NaN
26173512,Renegade (feat. Taylor Swift),49,2021-07-31,Big Red Machine,https://open.spotify.com/track/1aU1wpYBSpP0M6I...,Vietnam,viral50,MOVE_DOWN,NaN
26173513,Letter to Jarad,50,2021-07-31,"LRN Slime, Shiloh Dynasty",https://open.spotify.com/track/508QhA2SncMbh5C...,Vietnam,viral50,MOVE_DOWN,NaN

In [39]:
#clean data to include only necessary columns 
chart_data_reduced_columns = chart_data[["title", "rank", "date",'artist', "region", "chart", "streams"]]

#print dataframe
chart_data_reduced_columns

,title,rank,date,artist,region,chart,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,Argentina,top200,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,Argentina,top200,223988.0
2,Reggaetón Lento (Bailemos),3,2017-01-01,CNCO,Argentina,top200,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",Argentina,top200,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,Argentina,top200,153956.0
...,...,...,...,...,...,...,...
26173509,BYE,46,2021-07-31,Jaden,Vietnam,viral50,NaN
26173510,Pillars,47,2021-07-31,My Anh,Vietnam,viral50,NaN
26173511,Gái Độc Thân,48,2021-07-31,Tlinh,Vietnam,viral50,NaN
26173512,Renegade (feat. Taylor Swift),49,2021-07-31,Big Red Machine,Vietnam,viral50,NaN
26173513,Letter to Jarad,50,2021-07-31,"LRN Slime, Shiloh Dynasty",Vietnam,viral50,NaN

In [40]:
# look for missing values
chart_data_reduced_columns.count()

title      26173503
rank       26173514
date       26173514
artist     26173496
region     26173514
chart      26173514
streams    20321904
dtype: int64

In [41]:
# drop null rows
chart_data_reduced_columns = chart_data_reduced_columns.dropna(how='any')

In [42]:
# verify counts
chart_data_reduced_columns.count()

title      20321897
rank       20321897
date       20321897
artist     20321897
region     20321897
chart      20321897
streams    20321897
dtype: int64

In [43]:
#split date column to include only the year 
chart_data_reduced_columns['date'] = chart_data_reduced_columns['date'].apply(lambda x: x.split("-")[0])

/var/folders/lf/_fj3_9ln3j5bmwl546qpzm1w0000gn/T/ipykernel_6526/2861652227.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chart_data_reduced_columns['date'] = chart_data_reduced_columns['date'].apply(lambda x: x.split("-")[0])

In [44]:
#print dataframe 
chart_data_reduced_columns

,title,rank,date,artist,region,chart,streams
0,Chantaje (feat. Maluma),1,2017,Shakira,Argentina,top200,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017,Ricky Martin,Argentina,top200,223988.0
2,Reggaetón Lento (Bailemos),3,2017,CNCO,Argentina,top200,210943.0
3,Safari,4,2017,"J Balvin, Pharrell Williams, BIA, Sky",Argentina,top200,173865.0
4,Shaky Shaky,5,2017,Daddy Yankee,Argentina,top200,153956.0
...,...,...,...,...,...,...,...
25276069,Ojalá (feat. Darell),196,2018,"De La Ghetto, Almighty, Bryant Myers",Uruguay,top200,1178.0
25276070,Lo Que Pasa en la Noche,197,2018,Mano Arriba,Uruguay,top200,1178.0
25276071,El Equivocado,198,2018,Mano Arriba,Uruguay,top200,1170.0
25276072,Que Fui Tu Amante,199,2018,El Gucci y Su Banda,Uruguay,top200,1165.0
25276073,Solo,200,2018,"Amenazzy, Lary Over",Uruguay,top200,1162.0

In [45]:
#group chart_data_reduced_columns by date, title, artist and region to sort data 
new_chart = chart_data_reduced_columns.groupby(['date',"title","artist",'region'])

#sum the total number of streams for song and artists for each region 
streams = new_chart['streams'].sum()

#create new dataframe 
charts_df = pd.DataFrame({"total streams": streams,})

#print dataframe 
charts_df

                                                                              total streams
date title                                     artist         region
2017 "All That Is or Ever Was or Ever Will Be" Alan Silvestri Poland                 3547.0
                                                              Turkey                 3764.0
     "Read All About It, Pt. III"              Emeli Sandé    Belgium               15971.0
                                                              Czech Republic         6855.0
                                                              Denmark                6967.0
...                                                                                     ...
2021 욱 (UGH!)                                  BTS            South Korea           43909.0
     친구                                        BTS            South Korea          356265.0
     키스는 다음에                                   LOONA          Indonesia             93903.0
     🪐                                         Coldplay       Belgium                7747.0
                                                              Costa Rica            24223.0

[404954 rows x 1 columns]

In [46]:
#create new csv with cleaned data 
charts_df.to_csv('spotify_charts.csv')